[sources.mongodb]
connection_url = "<configure me>" # fill this in!

[destination.postgres.credentials]
database = "<configure me>" # fill this in!
password = "<configure me>" # fill this in!
username = "<configure me>" # fill this in!
host = "<configure me>" # fill this in!
port = 5432
connect_timeout = 15
